<%@ Page Title="" Language="C#" MasterPageFile="~/Warehouse.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="Warehouse.Home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <h1>Cases</h1>
        <hr />
        <div class="card">
            <!-- Default panel contents -->
            <div class="card-header bg-info text-white">All Cases</div>

            <asp:Repeater ID="RepeaterCases" runat="server">
                <HeaderTemplate>
                    <table class="card-table table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Kind</th>
                                <th>Start</th>
                                <th>End</th>
                                <th>Status</th>
                                <th>Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                </HeaderTemplate>
                <ItemTemplate>
                    <tr>
                        <th><%# Eval("CaseName") %></th>
                        <td><%# Eval("CategoryName") %></td>
                        <td><%# Eval("KindName") %></td>
                        <td><%# Eval("StartTime") %></td>
                        <td><%# Eval("EndTime") %></td>
                        <td><%# Eval("StatusName") %></td>
                        <td><%# Eval("Cost") %></td>
                    </tr>
                </ItemTemplate>
                <FooterTemplate>
                    </tbody>
                    </table>
                </FooterTemplate>
            </asp:Repeater>
        </div>
        <div class="form-group">
            <div class="col-md-2"></div>
            <div class="col-md-6">
                <asp:Label ID="NoCaseData" runat="server" CssClass="text-danger"></asp:Label>
            </div>
        </div>

    <br/>
    <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CaseId,CategoryId1,KindId1,StatusId1" EmptyDataText="查無案件" ShowHeaderWhenEmpty="True">
        <Columns>
            <asp:TemplateField HeaderText="CaseId" InsertVisible="False" SortExpression="CaseId">
                <EditItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("CaseId") %>'></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("CaseId") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="CaseName" HeaderText="CaseName" SortExpression="CaseName" />
            <asp:BoundField DataField="CategoryName" HeaderText="CategoryName" SortExpression="CategoryName" />
            <asp:BoundField DataField="KindName" HeaderText="KindName" SortExpression="KindName" />
            <asp:BoundField DataField="StartTime" HeaderText="StartTime" SortExpression="StartTime" />
            <asp:BoundField DataField="EndTime" HeaderText="EndTime" SortExpression="EndTime" />
            <asp:BoundField DataField="StatusName" HeaderText="StatusName" SortExpression="StatusName" />
            <asp:BoundField DataField="Cost" HeaderText="Cost" SortExpression="Cost" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:WarehouseDBConnectionString %>" SelectCommand="select A.*,B.*,C.*,D.* from Cases as A inner join Category as B on A.CategoryId=B.CategoryId inner join Kind as C on A.KindId=C.KindId inner join Status as D on A.StatusId=D.StatusId"></asp:SqlDataSource>
</asp:Content>
